import { Batch, BatchSchedule } from '@/types/batch'

const createSchedule = (days: string[], startTime: string, endTime: string): BatchSchedule[] => 
  days.map(day => ({ day: day as BatchSchedule['day'], startTime, endTime }))

export const mockBatches: Batch[] = [
  {
    id: 'batch_1',
    name: 'EH-2024-B1',
    courseId: 'ethical_hacking',
    courseName: 'Ethical Hacking',
    instructorId: 'usr_4',
    instructorName: 'Ananya Iyer',
    mode: 'online',
    status: 'ongoing',
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-03-15'),
    schedule: createSchedule(['monday', 'wednesday', 'friday'], '19:00', '21:00'),
    maxCapacity: 25,
    enrolledCount: 18,
    availableSeats: 7,
    onlineLink: 'https://meet.synthoquest.com/eh-2024-b1',
    fee: 45000,
    discount: 0,
    description: 'Comprehensive ethical hacking course covering reconnaissance, scanning, exploitation, and post-exploitation techniques.',
    syllabus: [
      'Introduction to Ethical Hacking',
      'Reconnaissance and Footprinting',
      'Scanning Networks',
      'Enumeration',
      'Vulnerability Analysis',
      'System Hacking',
      'Malware Threats',
      'Sniffing',
      'Social Engineering',
      'Denial of Service',
      'Session Hijacking',
      'Evading IDS, Firewalls, and Honeypots',
      'Hacking Web Servers',
      'Hacking Web Applications',
      'SQL Injection',
      'Hacking Wireless Networks',
      'Hacking Mobile Platforms',
      'IoT Hacking',
      'Cloud Computing',
      'Cryptography',
    ],
    prerequisites: ['Basic networking knowledge', 'Linux fundamentals'],
    createdBy: 'usr_1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'batch_2',
    name: 'PT-2024-B1',
    courseId: 'penetration_testing',
    courseName: 'Penetration Testing',
    instructorId: 'usr_3',
    instructorName: 'Vikram Singh',
    mode: 'hybrid',
    status: 'ongoing',
    startDate: new Date('2024-01-20'),
    endDate: new Date('2024-04-20'),
    schedule: createSchedule(['tuesday', 'thursday', 'saturday'], '18:00', '21:00'),
    maxCapacity: 20,
    enrolledCount: 12,
    availableSeats: 8,
    venue: 'SynthoQuest Lab, Floor 3',
    onlineLink: 'https://meet.synthoquest.com/pt-2024-b1',
    fee: 55000,
    discount: 5000,
    description: 'Advanced penetration testing course with hands-on labs covering network, web application, and mobile testing.',
    syllabus: [
      'Penetration Testing Methodologies',
      'Legal and Ethical Considerations',
      'Information Gathering',
      'Vulnerability Assessment',
      'Network Penetration Testing',
      'Web Application Penetration Testing',
      'Mobile Application Penetration Testing',
      'Wireless Penetration Testing',
      'Social Engineering Testing',
      'Red Team Operations',
      'Report Writing',
    ],
    prerequisites: ['Ethical Hacking certification', '2+ years IT experience'],
    createdBy: 'usr_1',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'batch_3',
    name: 'CS-2024-B1',
    courseId: 'cloud_security',
    courseName: 'Cloud Security',
    instructorId: 'usr_4',
    instructorName: 'Ananya Iyer',
    mode: 'online',
    status: 'ongoing',
    startDate: new Date('2024-01-22'),
    endDate: new Date('2024-03-22'),
    schedule: createSchedule(['monday', 'wednesday'], '20:00', '22:00'),
    maxCapacity: 30,
    enrolledCount: 15,
    availableSeats: 15,
    onlineLink: 'https://meet.synthoquest.com/cs-2024-b1',
    fee: 50000,
    discount: 0,
    description: 'Cloud security course covering AWS, Azure, and GCP security best practices.',
    syllabus: [
      'Cloud Computing Overview',
      'Shared Responsibility Model',
      'AWS Security',
      'Azure Security',
      'GCP Security',
      'Cloud Identity Management',
      'Cloud Network Security',
      'Data Protection in Cloud',
      'Cloud Compliance',
      'Cloud Incident Response',
    ],
    prerequisites: ['Basic cloud knowledge', 'Network fundamentals'],
    createdBy: 'usr_1',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'batch_4',
    name: 'NS-2023-B2',
    courseId: 'network_security',
    courseName: 'Network Security',
    instructorId: 'usr_3',
    instructorName: 'Vikram Singh',
    mode: 'offline',
    status: 'completed',
    startDate: new Date('2023-10-01'),
    endDate: new Date('2023-12-15'),
    schedule: createSchedule(['monday', 'tuesday', 'wednesday'], '10:00', '13:00'),
    maxCapacity: 20,
    enrolledCount: 18,
    availableSeats: 0,
    venue: 'SynthoQuest Training Center, Room 101',
    fee: 35000,
    discount: 0,
    description: 'Network security fundamentals covering firewalls, IDS/IPS, VPNs, and secure network design.',
    createdBy: 'usr_1',
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2023-12-15'),
  },
  {
    id: 'batch_5',
    name: 'CISSP-2024-B1',
    courseId: 'cissp_preparation',
    courseName: 'CISSP Preparation',
    instructorId: 'usr_1',
    instructorName: 'Arjun Sharma',
    mode: 'online',
    status: 'ongoing',
    startDate: new Date('2024-01-10'),
    endDate: new Date('2024-04-10'),
    schedule: createSchedule(['saturday', 'sunday'], '10:00', '14:00'),
    maxCapacity: 15,
    enrolledCount: 10,
    availableSeats: 5,
    onlineLink: 'https://meet.synthoquest.com/cissp-2024-b1',
    fee: 60000,
    discount: 10000,
    description: 'Comprehensive CISSP exam preparation covering all 8 domains.',
    syllabus: [
      'Security and Risk Management',
      'Asset Security',
      'Security Architecture and Engineering',
      'Communication and Network Security',
      'Identity and Access Management',
      'Security Assessment and Testing',
      'Security Operations',
      'Software Development Security',
    ],
    prerequisites: ['5+ years of IT security experience'],
    createdBy: 'usr_1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'batch_6',
    name: 'CSF-2024-B1',
    courseId: 'cyber_security_fundamentals',
    courseName: 'Cyber Security Fundamentals',
    instructorId: 'usr_4',
    instructorName: 'Ananya Iyer',
    mode: 'offline',
    status: 'ongoing',
    startDate: new Date('2024-01-25'),
    endDate: new Date('2024-02-25'),
    schedule: createSchedule(['monday', 'wednesday', 'friday'], '18:00', '20:00'),
    maxCapacity: 30,
    enrolledCount: 22,
    availableSeats: 8,
    venue: 'SynthoQuest Training Center, Room 201',
    fee: 25000,
    discount: 0,
    description: 'Entry-level cybersecurity course for beginners.',
    syllabus: [
      'Introduction to Cybersecurity',
      'Types of Cyber Threats',
      'Security Principles',
      'Access Control',
      'Network Security Basics',
      'Cryptography Fundamentals',
      'Security Policies',
      'Incident Response Basics',
    ],
    prerequisites: [],
    createdBy: 'usr_2',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'batch_7',
    name: 'CEH-2024-B1',
    courseId: 'ceh_certification',
    courseName: 'CEH Certification',
    instructorId: 'usr_3',
    instructorName: 'Vikram Singh',
    mode: 'hybrid',
    status: 'ongoing',
    startDate: new Date('2024-01-18'),
    endDate: new Date('2024-03-18'),
    schedule: createSchedule(['tuesday', 'thursday'], '19:00', '21:30'),
    maxCapacity: 20,
    enrolledCount: 14,
    availableSeats: 6,
    venue: 'SynthoQuest Lab, Floor 2',
    onlineLink: 'https://meet.synthoquest.com/ceh-2024-b1',
    fee: 50000,
    discount: 0,
    description: 'Certified Ethical Hacker exam preparation course.',
    prerequisites: ['Basic networking', 'Linux knowledge'],
    createdBy: 'usr_1',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: 'batch_8',
    name: 'IR-2024-B1',
    courseId: 'incident_response',
    courseName: 'Incident Response',
    instructorId: 'usr_4',
    instructorName: 'Ananya Iyer',
    mode: 'online',
    status: 'ongoing',
    startDate: new Date('2024-01-12'),
    endDate: new Date('2024-02-28'),
    schedule: createSchedule(['saturday'], '14:00', '18:00'),
    maxCapacity: 25,
    enrolledCount: 16,
    availableSeats: 9,
    onlineLink: 'https://meet.synthoquest.com/ir-2024-b1',
    fee: 40000,
    discount: 0,
    description: 'Incident response and handling course for security professionals.',
    prerequisites: ['2+ years security experience'],
    createdBy: 'usr_1',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 'batch_9',
    name: 'SA-2024-B1',
    courseId: 'security_analytics',
    courseName: 'Security Analytics',
    instructorId: 'usr_3',
    instructorName: 'Vikram Singh',
    mode: 'online',
    status: 'upcoming',
    startDate: new Date('2024-02-15'),
    endDate: new Date('2024-04-15'),
    schedule: createSchedule(['monday', 'wednesday'], '19:00', '21:00'),
    maxCapacity: 25,
    enrolledCount: 8,
    availableSeats: 17,
    onlineLink: 'https://meet.synthoquest.com/sa-2024-b1',
    fee: 45000,
    discount: 5000,
    description: 'Security analytics and SIEM operations course.',
    prerequisites: ['Basic security knowledge'],
    createdBy: 'usr_1',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'batch_10',
    name: 'CompTIA-2023-B3',
    courseId: 'comptia_security',
    courseName: 'CompTIA Security+',
    instructorId: 'usr_1',
    instructorName: 'Arjun Sharma',
    mode: 'online',
    status: 'completed',
    startDate: new Date('2023-11-01'),
    endDate: new Date('2024-01-15'),
    schedule: createSchedule(['tuesday', 'thursday', 'saturday'], '18:00', '20:00'),
    maxCapacity: 25,
    enrolledCount: 20,
    availableSeats: 0,
    onlineLink: 'https://meet.synthoquest.com/comptia-2023-b3',
    fee: 30000,
    discount: 0,
    description: 'CompTIA Security+ certification preparation.',
    createdBy: 'usr_1',
    createdAt: new Date('2023-10-15'),
    updatedAt: new Date('2024-01-15'),
  },
]

export function getBatchById(id: string): Batch | undefined {
  return mockBatches.find(batch => batch.id === id)
}

export function getBatchesByStatus(status: string): Batch[] {
  return mockBatches.filter(batch => batch.status === status)
}

export function getBatchesByCourse(courseId: string): Batch[] {
  return mockBatches.filter(batch => batch.courseId === courseId)
}

export function getBatchesByInstructor(instructorId: string): Batch[] {
  return mockBatches.filter(batch => batch.instructorId === instructorId)
}

export function getUpcomingBatches(): Batch[] {
  return mockBatches.filter(batch => batch.status === 'upcoming' || batch.status === 'ongoing')
}

export function getAvailableBatches(): Batch[] {
  return mockBatches.filter(batch => batch.availableSeats > 0 && batch.status !== 'completed')
}