import { Intern } from '@/types/intern'
import { generateId } from '@/lib/utils'

const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000)

export const mockInterns: Intern[] = [
  {
    id: 'intern_1',
    name: 'Sneha Gupta',
    email: 'sneha.gupta@email.com',
    phone: '+91 98765 44444',
    internshipType: 'paid',
    duration: '3_months',
    department: 'training',
    college: 'BITS Pilani',
    degree: 'MSc Computer Science',
    year: '2',
    skills: ['Java', 'Python', 'Machine Learning'],
    resumeUrl: 'https://drive.google.com/file/sneha-resume',
    linkedinUrl: 'https://linkedin.com/in/snehagupta',
    portfolioUrl: 'https://github.com/snehagupta',
    startDate: daysAgo(15),
    expectedEndDate: daysAgo(-75),
    status: 'active',
    source: 'website',
    leadId: 'lead_intern_4',
    convertedFrom: 'lead_intern_4',
    convertedAt: daysAgo(15),
    convertedBy: 'usr_2',
    supervisorId: 'usr_3',
    supervisorName: 'Vikram Singh',
    stipend: 8000,
    notes: 'Currently interning in training department, performing well',
    approvalStatus: 'approved',
    approvedBy: 'usr_2',
    approvedAt: daysAgo(18),
    createdAt: daysAgo(22),
    updatedAt: daysAgo(15),
  },
  {
    id: 'intern_2',
    name: 'Vikash Kumar',
    email: 'vikash.kumar@email.com',
    phone: '+91 98765 33333',
    internshipType: 'paid',
    duration: '3_months',
    department: 'sales',
    college: 'Delhi University',
    degree: 'BBA',
    year: '3',
    skills: ['Communication', 'MS Office', 'CRM'],
    resumeUrl: 'https://drive.google.com/file/vikash-resume',
    linkedinUrl: 'https://linkedin.com/in/vikashkumar',
    startDate: daysAgo(-5),
    expectedEndDate: daysAgo(-95),
    status: 'offered',
    source: 'job_portal',
    leadId: 'lead_intern_3',
    convertedFrom: 'lead_intern_3',
    convertedAt: daysAgo(-3),
    convertedBy: 'usr_2',
    supervisorId: 'usr_4',
    supervisorName: 'Ananya Sharma',
    stipend: 7000,
    notes: 'Offer extended, awaiting confirmation by end of week',
    approvalStatus: 'approved',
    approvedBy: 'usr_2',
    approvedAt: daysAgo(3),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },
  {
    id: 'intern_3',
    name: 'Priya Sundarajan',
    email: 'priya.sundarajan@email.com',
    phone: '+91 98765 22222',
    internshipType: 'unpaid',
    duration: '2_months',
    department: 'marketing',
    college: 'IIT Madras',
    degree: 'MBA Marketing',
    year: '2',
    skills: ['Digital Marketing', 'Content Writing', 'SEO'],
    resumeUrl: 'https://drive.google.com/file/priya-resume',
    linkedinUrl: 'https://linkedin.com/in/priyasundarajan',
    portfolioUrl: 'https://priyawrites.com',
    startDate: daysAgo(-10),
    expectedEndDate: daysAgo(-70),
    status: 'shortlisted',
    source: 'campus',
    leadId: 'lead_intern_2',
    convertedFrom: 'lead_intern_2',
    notes: 'Excellent communication skills, portfolio looks great. Technical round scheduled.',
    approvalStatus: 'pending',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },
  {
    id: 'intern_4',
    name: 'Arjun Menon',
    email: 'arjun.menon@email.com',
    phone: '+91 98765 11111',
    internshipType: 'paid',
    duration: '3_months',
    department: 'training',
    college: 'VIT University, Vellore',
    degree: 'B.Tech Computer Science',
    year: '3',
    skills: ['Python', 'Networking', 'Linux'],
    resumeUrl: 'https://drive.google.com/file/arjun-resume',
    linkedinUrl: 'https://linkedin.com/in/arjunmenon',
    startDate: daysAgo(-20),
    expectedEndDate: daysAgo(-110),
    status: 'applied',
    source: 'website',
    leadId: 'lead_intern_1',
    convertedFrom: 'lead_intern_1',
    notes: 'Strong technical background, referred by alumni. Needs HR approval.',
    approvalStatus: 'pending',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'intern_5',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@email.com',
    phone: '+91 98765 66666',
    internshipType: 'paid',
    duration: '2_months',
    department: 'training',
    college: 'NIT Trichy',
    degree: 'B.Tech IT',
    year: '4',
    skills: ['Cyber Security', 'CTF', 'Linux'],
    resumeUrl: 'https://drive.google.com/file/ananya-resume',
    linkedinUrl: 'https://linkedin.com/in/ananyaiyer',
    portfolioUrl: 'https://github.com/ananyaiyer',
    startDate: daysAgo(-15),
    expectedEndDate: daysAgo(-75),
    status: 'applied',
    source: 'referral',
    leadId: 'lead_intern_6',
    convertedFrom: 'lead_intern_6',
    notes: 'Referred by current trainer, strong CTF background. High potential candidate.',
    approvalStatus: 'pending',
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: 'intern_6',
    name: 'Rohan Patel',
    email: 'rohan.patel@email.com',
    phone: '+91 98765 77777',
    internshipType: 'paid',
    duration: '3_months',
    department: 'training',
    college: 'IIIT Hyderabad',
    degree: 'B.Tech CSE',
    year: '3',
    skills: ['Python', 'Machine Learning', 'Deep Learning'],
    resumeUrl: 'https://drive.google.com/file/rohan-resume',
    linkedinUrl: 'https://linkedin.com/in/rohanpatel',
    startDate: daysAgo(60),
    expectedEndDate: daysAgo(-30),
    actualEndDate: daysAgo(5),
    status: 'completed',
    source: 'campus',
    performanceRating: 4.5,
    feedback: 'Excellent performance, delivered ML model for security analytics. Highly recommended for future opportunities.',
    stipend: 8000,
    notes: 'Completed internship with excellent feedback',
    approvalStatus: 'approved',
    approvedBy: 'usr_2',
    approvedAt: daysAgo(90),
    createdAt: daysAgo(95),
    updatedAt: daysAgo(5),
  },
  {
    id: 'intern_7',
    name: 'Kavya Sharma',
    email: 'kavya.sharma@email.com',
    phone: '+91 98765 88888',
    internshipType: 'unpaid',
    duration: '1_month',
    department: 'content',
    college: 'Christ University',
    degree: 'BJMC',
    year: '3',
    skills: ['Content Writing', 'Social Media', 'Video Editing'],
    resumeUrl: 'https://drive.google.com/file/kavya-resume',
    linkedinUrl: 'https://linkedin.com/in/kavyasharma',
    startDate: daysAgo(30),
    expectedEndDate: daysAgo(0),
    status: 'active',
    source: 'website',
    supervisorId: 'usr_8',
    supervisorName: 'Kavitha Nair',
    notes: 'Working on social media content and blog posts',
    approvalStatus: 'approved',
    approvedBy: 'usr_2',
    approvedAt: daysAgo(35),
    createdAt: daysAgo(40),
    updatedAt: daysAgo(10),
  },
  {
    id: 'intern_8',
    name: 'Aditya Verma',
    email: 'aditya.verma@email.com',
    phone: '+91 98765 99999',
    internshipType: 'paid',
    duration: '3_months',
    department: 'training',
    college: 'Manipal University',
    degree: 'B.Tech ECE',
    year: '4',
    skills: ['Networking', 'Linux', 'Python'],
    startDate: daysAgo(45),
    expectedEndDate: daysAgo(-45),
    status: 'dropped',
    source: 'referral',
    stipend: 7500,
    notes: 'Left due to personal reasons after 6 weeks',
    approvalStatus: 'approved',
    approvedBy: 'usr_2',
    approvedAt: daysAgo(50),
    createdAt: daysAgo(55),
    updatedAt: daysAgo(15),
  },
]

export function getInternById(id: string): Intern | undefined {
  return mockInterns.find(intern => intern.id === id)
}

export function getInternsByStatus(status: string): Intern[] {
  return mockInterns.filter(intern => intern.status === status)
}

export function getInternsByDepartment(department: string): Intern[] {
  return mockInterns.filter(intern => intern.department === department)
}

export function getActiveInterns(): Intern[] {
  return mockInterns.filter(intern => intern.status === 'active')
}

export function getInternsNeedingApproval(): Intern[] {
  return mockInterns.filter(intern => intern.approvalStatus === 'pending')
}

export function getInternStats(): {
  total: number
  active: number
  completed: number
  pending: number
  byDepartment: Record<string, number>
} {
  return {
    total: mockInterns.length,
    active: mockInterns.filter(i => i.status === 'active').length,
    completed: mockInterns.filter(i => i.status === 'completed').length,
    pending: mockInterns.filter(i => i.approvalStatus === 'pending').length,
    byDepartment: mockInterns.reduce((acc, intern) => {
      acc[intern.department] = (acc[intern.department] || 0) + 1
      return acc
    }, {} as Record<string, number>),
  }
}