import { Student, Enrollment } from '@/types/student'

const createEnrollment = (
  id: string,
  studentId: string,
  courseName: string,
  batchId: string,
  batchName: string,
  courseFee: number,
  paidAmount: number,
  status: Enrollment['status'],
  progress: number,
  instructor: string
): Enrollment => ({
  id,
  studentId,
  courseId: courseName.toLowerCase().replace(/\s+/g, '_'),
  courseName,
  batchId,
  batchName,
  status,
  enrolledAt: new Date(Date.now() - Math.random() * 90 * 24 * 60 * 60 * 1000),
  enrollmentFee: 5000,
  courseFee,
  discount: Math.random() > 0.7 ? 5000 : 0,
  totalFee: courseFee - (Math.random() > 0.7 ? 5000 : 0),
  paidAmount,
  dueAmount: courseFee - paidAmount - (Math.random() > 0.7 ? 5000 : 0),
  paymentPlan: Math.random() > 0.5 ? 'full' : 'installment',
  startDate: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000),
  expectedEndDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
  completedDate: status === 'completed' ? new Date() : undefined,
  instructor,
  progress,
  certificateIssued: status === 'completed',
  certificateId: status === 'completed' ? `cert_${id}` : undefined,
})

export const mockStudents: Student[] = [
  {
    id: 'stu_1',
    name: 'Meera Krishnan',
    email: 'meera.krishnan@email.com',
    phone: '+91 87654 32107',
    address: '42, Park Street, T. Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600017',
    qualification: 'B.Tech Computer Science',
    occupation: 'Student',
    status: 'active',
    source: 'referral',
    leadId: 'lead_8',
    convertedFrom: 'Sneha Reddy',
    convertedAt: new Date('2024-01-12'),
    convertedBy: 'usr_6',
    notes: 'College student, interested in internship opportunity',
    enrollments: [
      createEnrollment('enr_1', 'stu_1', 'Ethical Hacking', 'batch_1', 'EH-2024-B1', 45000, 45000, 'in_progress', 65, 'Ananya Iyer'),
    ],
    totalPaid: 45000,
    totalDue: 0,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'stu_2',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@email.com',
    phone: '+91 98765 43222',
    alternatePhone: '+91 87654 32222',
    address: '15, MG Road, Koramangala',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560034',
    qualification: 'MCA',
    occupation: 'Software Developer',
    company: 'Tech Solutions Pvt Ltd',
    experience: '3 years',
    status: 'active',
    source: 'ads',
    convertedFrom: 'Rahul Kumar',
    convertedAt: new Date('2024-01-15'),
    convertedBy: 'usr_5',
    notes: 'Experienced developer looking to transition into security',
    enrollments: [
      createEnrollment('enr_2', 'stu_2', 'Penetration Testing', 'batch_2', 'PT-2024-B1', 55000, 35000, 'in_progress', 30, 'Vikram Singh'),
    ],
    totalPaid: 35000,
    totalDue: 20000,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'stu_3',
    name: 'Ananya Sharma',
    email: 'ananya.sharma@email.com',
    phone: '+91 98765 43223',
    address: '78, Sector 15, Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    pincode: '201301',
    qualification: 'B.Sc IT',
    occupation: 'IT Support',
    company: 'Global Corp',
    experience: '2 years',
    status: 'active',
    source: 'organic',
    convertedFrom: 'Sneha Reddy',
    convertedAt: new Date('2024-01-10'),
    convertedBy: 'usr_6',
    notes: 'Interested in cloud security certification',
    enrollments: [
      createEnrollment('enr_3', 'stu_3', 'Cloud Security', 'batch_3', 'CS-2024-B1', 50000, 50000, 'in_progress', 45, 'Ananya Iyer'),
    ],
    totalPaid: 50000,
    totalDue: 0,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'stu_4',
    name: 'Vikram Rathore',
    email: 'vikram.rathore@email.com',
    phone: '+91 98765 43224',
    address: '23, Civil Lines, Jaipur',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302006',
    qualification: 'B.Tech',
    occupation: 'Network Engineer',
    company: 'Data Networks',
    experience: '5 years',
    status: 'completed',
    source: 'referral',
    convertedFrom: 'Rahul Kumar',
    convertedAt: new Date('2023-10-15'),
    convertedBy: 'usr_5',
    notes: 'Completed course successfully',
    enrollments: [
      createEnrollment('enr_4', 'stu_4', 'Network Security', 'batch_4', 'NS-2023-B2', 35000, 35000, 'completed', 100, 'Vikram Singh'),
    ],
    totalPaid: 35000,
    totalDue: 0,
    createdAt: new Date('2023-10-15'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: 'stu_5',
    name: 'Priya Nair',
    email: 'priya.nair@email.com',
    phone: '+91 98765 43225',
    address: '56, Kalpana Nagar, Kochi',
    city: 'Kochi',
    state: 'Kerala',
    pincode: '682016',
    qualification: 'M.Tech',
    occupation: 'Security Analyst',
    company: 'SecureTech',
    experience: '4 years',
    status: 'active',
    source: 'ads',
    convertedFrom: 'Sneha Reddy',
    convertedAt: new Date('2024-01-08'),
    convertedBy: 'usr_6',
    notes: 'Preparing for CISSP certification',
    enrollments: [
      createEnrollment('enr_5', 'stu_5', 'CISSP Preparation', 'batch_5', 'CISSP-2024-B1', 60000, 40000, 'in_progress', 55, 'Arjun Sharma'),
    ],
    totalPaid: 40000,
    totalDue: 20000,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-28'),
  },
  {
    id: 'stu_6',
    name: 'Arjun Menon',
    email: 'arjun.menon@email.com',
    phone: '+91 98765 43226',
    address: '12, Anna Nagar, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600040',
    qualification: 'BCA',
    occupation: 'Fresher',
    status: 'active',
    source: 'organic',
    convertedFrom: 'Rahul Kumar',
    convertedAt: new Date('2024-01-18'),
    convertedBy: 'usr_5',
    notes: 'Entry level, looking for career in cybersecurity',
    enrollments: [
      createEnrollment('enr_6', 'stu_6', 'Cyber Security Fundamentals', 'batch_6', 'CSF-2024-B1', 25000, 25000, 'in_progress', 20, 'Ananya Iyer'),
    ],
    totalPaid: 25000,
    totalDue: 0,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'stu_7',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@student@email.com',
    phone: '+91 98765 43227',
    address: '34, Banjara Hills, Hyderabad',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500034',
    qualification: 'B.Tech CSE',
    occupation: 'QA Engineer',
    company: 'TestPro Solutions',
    experience: '2 years',
    status: 'active',
    source: 'referral',
    convertedFrom: 'Sneha Reddy',
    convertedAt: new Date('2024-01-12'),
    convertedBy: 'usr_6',
    notes: 'Interested in CEH certification',
    enrollments: [
      createEnrollment('enr_7', 'stu_7', 'CEH Certification', 'batch_7', 'CEH-2024-B1', 50000, 30000, 'in_progress', 40, 'Vikram Singh'),
    ],
    totalPaid: 30000,
    totalDue: 20000,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'stu_8',
    name: 'Karthik Suresh',
    email: 'karthik.suresh@email.com',
    phone: '+91 98765 43228',
    address: '89, Indiranagar, Bangalore',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560038',
    qualification: 'M.Sc CS',
    occupation: 'SOC Analyst',
    company: 'CyberDefense Inc',
    experience: '3 years',
    status: 'active',
    source: 'ads',
    convertedFrom: 'Rahul Kumar',
    convertedAt: new Date('2024-01-05'),
    convertedBy: 'usr_5',
    notes: 'Working professional, weekend batch preferred',
    enrollments: [
      createEnrollment('enr_8', 'stu_8', 'Incident Response', 'batch_8', 'IR-2024-B1', 40000, 40000, 'in_progress', 70, 'Ananya Iyer'),
      createEnrollment('enr_9', 'stu_8', 'Security Analytics', 'batch_9', 'SA-2024-B1', 45000, 25000, 'enrolled', 0, 'Vikram Singh'),
    ],
    totalPaid: 65000,
    totalDue: 20000,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-30'),
  },
  {
    id: 'stu_9',
    name: 'Divya Chandran',
    email: 'divya.chandran@email.com',
    phone: '+91 98765 43229',
    address: '45, Powai, Mumbai',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400076',
    qualification: 'B.E IT',
    occupation: 'System Admin',
    company: 'Finance Corp',
    experience: '4 years',
    status: 'completed',
    source: 'organic',
    convertedFrom: 'Sneha Reddy',
    convertedAt: new Date('2023-11-10'),
    convertedBy: 'usr_6',
    notes: 'Completed CompTIA Security+',
    enrollments: [
      createEnrollment('enr_10', 'stu_9', 'CompTIA Security+', 'batch_10', 'CompTIA-2023-B3', 30000, 30000, 'completed', 100, 'Arjun Sharma'),
    ],
    totalPaid: 30000,
    totalDue: 0,
    createdAt: new Date('2023-11-10'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'stu_10',
    name: 'Rohan Patil',
    email: 'rohan.patil@email.com',
    phone: '+91 98765 43230',
    address: '67, Koregaon Park, Pune',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411001',
    qualification: 'B.Tech',
    occupation: 'Software Engineer',
    company: 'TechStart',
    experience: '2 years',
    status: 'dropped',
    source: 'ads',
    convertedFrom: 'Rahul Kumar',
    convertedAt: new Date('2023-12-01'),
    convertedBy: 'usr_5',
    notes: 'Dropped due to job relocation',
    enrollments: [
      createEnrollment('enr_11', 'stu_10', 'Ethical Hacking', 'batch_1', 'EH-2024-B1', 45000, 20000, 'dropped', 25, 'Ananya Iyer'),
    ],
    totalPaid: 20000,
    totalDue: 25000,
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'stu_11',
    name: 'Aisha Khan',
    email: 'aisha.khan@email.com',
    phone: '+91 98765 43231',
    address: '22, Salt Lake, Kolkata',
    city: 'Kolkata',
    state: 'West Bengal',
    pincode: '700091',
    qualification: 'MCA',
    occupation: 'IT Consultant',
    company: 'Consulting Partners',
    experience: '6 years',
    status: 'active',
    source: 'referral',
    convertedFrom: 'Sneha Reddy',
    convertedAt: new Date('2024-01-20'),
    convertedBy: 'usr_6',
    notes: 'Corporate sponsored training',
    enrollments: [
      createEnrollment('enr_12', 'stu_11', 'Penetration Testing', 'batch_2', 'PT-2024-B1', 55000, 55000, 'enrolled', 5, 'Vikram Singh'),
    ],
    totalPaid: 55000,
    totalDue: 0,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'stu_12',
    name: 'Suresh Venkatesh',
    email: 'suresh.venkatesh@email.com',
    phone: '+91 98765 43232',
    address: '90, Velachery, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600042',
    qualification: 'B.Sc CS',
    occupation: 'Technical Writer',
    company: 'DocuTech',
    experience: '3 years',
    status: 'on_hold',
    source: 'organic',
    convertedFrom: 'Rahul Kumar',
    convertedAt: new Date('2024-01-02'),
    convertedBy: 'usr_5',
    notes: 'On hold due to personal reasons',
    enrollments: [
      createEnrollment('enr_13', 'stu_12', 'Cloud Security', 'batch_3', 'CS-2024-B1', 50000, 15000, 'enrolled', 0, 'Ananya Iyer'),
    ],
    totalPaid: 15000,
    totalDue: 35000,
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-15'),
  },
]

export function getStudentById(id: string): Student | undefined {
  return mockStudents.find(student => student.id === id)
}

export function getStudentsByStatus(status: string): Student[] {
  return mockStudents.filter(student => student.status === status)
}

export function getStudentsByCourse(course: string): Student[] {
  return mockStudents.filter(student => 
    student.enrollments.some(e => e.courseName === course)
  )
}

export function getActiveStudents(): Student[] {
  return mockStudents.filter(s => s.status === 'active')
}

export function getStudentsWithDuePayments(): Student[] {
  return mockStudents.filter(s => s.totalDue > 0)
}